name: 'Store Artifact Cache'
description: 'Stores to Artifact Cache'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Store to Artifact Cache
      if: success()
      id: store_cache
      continue-on-error: true
      shell: bash
      run: $ARTIFACT_CACHE_CMD store $ARTIFACT_CACHE_CMD_OPTS

    - name: Warn on Cache Store Failure
      if: steps.store_cache.outcome == 'failure'
      shell: bash
      run: 'echo "WARNING: Failed to store in the Artifact Cache."'

    - name: Persist Artifact Cache Logs
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ inputs.artifact-name }}
        path: '~/.develocity/artifact-cache/artifact-cache.log'
        retention-days: 7
