name: 'Store Artifact Cache'
description: 'Stores to Artifact Cache'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Store to Artifact Cache
      if: success() && env.ARTIFACT_CACHE_REPO_PASSWORD != ''
      id: store_cache
      continue-on-error: true
      shell: bash
      run: $ARTIFACT_CACHE_CMD store $ARTIFACT_CACHE_CMD_OPTS

    - name: Warn on Cache Store Failure
      if: env.ARTIFACT_CACHE_REPO_PASSWORD != '' && steps.store_cache.outcome == 'failure'
      shell: bash
      run: 'echo "WARNING: Failed to store in the Artifact Cache."'

    - name: Persist Artifact Cache Logs
      if: env.ARTIFACT_CACHE_REPO_PASSWORD != ''
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: '~/.develocity/artifact-cache/artifact-cache.log'
        retention-days: 7
