name: Non task caching tests

on:
  push:
    branches: [ gk/nonTaskCacheTests ]
  workflow_dispatch:

jobs:
  runTests:
    name: Experiments
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [ 'help', ':app:assembleProdDebug' ]
        exp:
          - cache: 'transforms'
            args: '-Dscan.tag.baseline-transforms'
          - cache: 'transforms'
            args: '-Dscan.tag.transformCachingDisabled -Dorg.gradle.internal.transform-caching-disabled'
          - cache: 'kotlin-dsl'
            args: '-Dscan.tag.baseline-kotlin-dsl'
          - cache: 'kotlin-dsl'
            args: '-Dscan.tag.kotlinScriptCachingDisabled -Dorg.gradle.internal.kotlin-script-caching-disabled'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Clear Gradle user home caches we don't want
        env:
          GRADLE_CACHE_REMOTE_PUSH: "true"
          GRADLE_CACHE_REMOTE_PATH: "cache/android-cache-fix-plugin-exp-non-task"
          GRADLE_CACHE_REMOTE_URL: "https://ge.solutions-team.gradle.com/cache/android-cache-fix-plugin-exp-non-task"
        run: |
          cache='${{ matrix.exp.cache }}'
          args='${{ matrix.exp.args }}'
          
          echo "Test caches/*/$cache removal with $args"

          echo "Running build once to fully populate Gradle User Home"
          ./gradlew ${{ matrix.task }} -Dscan.tag.remote-cache-experiment-init --no-daemon --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true -Dgradle.enterprise.url=https://ge.solutions-team.gradle.com/ 
          ./gradlew --stop
          
          echo "Removing $cache from $homeDir/caches"
          rm -rf ~/.gradle/caches/*/$cache
          rm -rf ~/.gradle/caches/$cache-* # Also remove the transforms for Gradle 8.7
          
          # Always remove the local build cache, since we are testing connection with remote build cache
          rm -rf ~/.gradle/caches/build-cache-1

          echo "Running build again with --${args}"
          ./gradlew ${{ matrix.task }} --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true -Dscan.uploadInBackground=false -Dgradle.enterprise.url=https://ge.solutions-team.gradle.com $args