name: Non task caching tests

on:
  push:
    branches: [ gk/nonTaskCacheTests ]
  workflow_dispatch:

jobs:
  runTests:
    name: Non task caching tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arguments: ['-Dscan.tag.baseline', '-Dscan.tag.transformCachingDisabled -Dorg.gradle.internal.transform-caching-disabled', '-Dscan.tag.kotlinScriptCachingDisabled -Dorg.gradle.experimental.kotlin-script-caching-disabled']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
          gradle-home-cache-excludes: |
            caches/build-cache-*
            caches/transforms-*
            caches/*/transforms
            caches/*/kotlin-dsl
            caches/*/groovy-dsl
      - name: Clear Gradle user home caches we don't want
        run: rm -rf $HOME/.gradle/caches/build-cache-* $HOME/.gradle/caches/transforms-* $HOME/.gradle/caches/*/transforms $HOME/.gradle/caches/*/kotlin-dsl $HOME/.gradle/caches/*/groovy-dsl
      - name: Run sanityCheck
        run: ./gradlew help -Dscan.tag.nonTaskCache -Dgradle.cache.local.enabled=false --no-configuration-cache ${{ matrix.arguments }}